team:
   name: Cargo tu encargo
   members:
      - user: c.caicedob
        percentage: <0 a 100>
      - user: of.munoz
        percentage: <0 a 100>
      - user: mar-torr
        percentage: <0 a 100>
      - user: mc.torreso1
        percentage: <0 a 100>
board: https://github.com/orgs/MISW-4301-Desarrollo-Apps-en-la-Nube/projects/336
docs: <link al github pages del equipo>
users_app:
  folder: users_app
  image_name: users_app
  image_tag: v1.0.0
  authors:
    - of.munoz
posts_app:
  folder: posts_app
  image_name: posts_app
  image_tag: v1.0.0
  authors:
    - mar-torr
offers_app:
  folder: offers_app
  image_name: offers_app
  image_tag: v1.0.0
  authors:
    - <usuario uniandes>
routes_app:
  folder: routes_app
  image_name: routes_app
  image_tag: v1.0.0
  authors:
    - <usuario uniandes>
