team:
   name: Cargo tu encargo
   members:
      - user: c.caicedob
        percentage: 25
      - user: of.munoz
        percentage: 25
      - user: mar-torr
        percentage: 25
      - user: mc.torreso1
        percentage: 25
board: https://github.com/orgs/MISW-4301-Desarrollo-Apps-en-la-Nube/projects/336
docs: https://refactored-dollop-qwj93z8.pages.github.io/
users_app:
  folder: users_app
  image_name: users_app
  image_tag: v1.0.0
  authors:
    - of.munoz
posts_app:
  folder: posts_app
  image_name: posts_app
  image_tag: v1.0.0
  authors:
    - mar-torr
offers_app:
  folder: offers_app
  image_name: offers_app
  image_tag: v1.0.0
  authors:
    - c.caicedob
routes_app:
  folder: routes_app
  image_name: routes_app
  image_tag: v1.0.0
  authors:
    - mc.torreso1
