name: Entrega 1 - Evaluador Implementación
on: workflow_dispatch
jobs:
  evaluador:
    uses: MISW-4301-Desarrollo-Apps-en-la-Nube/recursos-evaluador/.github/workflows/ci_evaluador_entrega1_k8s.yml@main
