name: Entrega 2 - Evaluador Implementación
on:
  workflow_dispatch:
    inputs:
      environment:
        type: choice
        required: true
        description: 'Select the target environment'
        options:
          - student1
          - student2
          - student3
          - student4
          - tutor
      execution:
        type: choice
        required: true
        description: 'Select the execution mode'
        options:
          - run_all
          - run_rf003
          - run_rf004
          - run_rf005
jobs:
  evaluador:
    uses: MISW-4301-Desarrollo-Apps-en-la-Nube/recursos-evaluador/.github/workflows/ci_evaluador_entrega2.yml@main
    with:
      environment: ${{ inputs.environment }}
      execution: ${{ inputs.execution }}
    secrets: inherit
